" Author: Nelson Weirich
" Source: https://github.com/NelsonWeirich/dotfiles

"------------------------------------------------------------
" VIM XDG Base Directory support
" Vim follow XDG by https://blog.joren.ga/tools/vim-sdg
"
if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"     | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"    | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME = $HOME."/.local/share" | endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p', 0700)
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p', 0700)

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p', 0700)
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir, 'p', 0700)

if !has('nvim') 
    set viminfofile=$XDG_CACHE_HOME/vim/viminfo
endif

"------------------------------------------------------------
let mapleader=","

set title
set bg=light
set go=a
set mouse=a
set nohlsearch
set clipboard+=unnamedplus
set noshowmode
set noruler
set laststatus=2
set noshowcmd

set hidden
set wildmenu
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set nostartofline
set confirm

"------------------------------------------------------------
"" Indentation options

set autoindent
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set smarttab

set linebreak
set textwidth=81
set colorcolumn=80

set incsearch
set showmatch
set cursorline

set undolevels=1000 

" Basic settings
    nnoremap c "_c
    set nocompatible
    filetype indent plugin on
    syntax on
    set encoding=utf-8
    set number relativenumber
" Enable autocompletion
    set wildmode=longest,list,full
" Disables automatic commenting on newline
    autocmd FileType * setlocal formatoptions-=c formatoptions-=r
" Perform dot commands over visual blocks
    vnoremap . :normal .<CR>
" Speel-cheker with <leader>o
    map <leader>o :setlocal spell! spelllang=en_gb<CR>
" Splits open at the bottom and right
    set splitbelow splitright
" Shortcut split navigation
    map <C-h> <C-w>h
    map <C-j> <C-w>j
    map <C-k> <C-w>k
    map <C-l> <C-w>l
 " Disable arrow keys in Normal mode
    no <Up> <Nop>
    no <Down> <Nop>
    no <Left> <Nop>
    no <Right> <Nop>
" Disable arrow keys in Insert mode
    ino <Up> <Nop>
    ino <Down> <Nop>
    ino <Left> <Nop>
    ino <Right> <Nop>
" Replace yank line with Y
    map Y y$
" Replace ex mode with gq
    map Q gq
" Alias replace all with S
    nnoremap S :%s//g<Left><Left>

