#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

~/.local/bin/setbg &			# set the background with the `setbg` script
[ ! -s ~/.config/mpd/mpd.pid ] &&
    mpd &			# music player daemon-you might prefer it as a service though
~/.local/bin/remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle

# Statusbar loop
# Bluetooth: cat /sys/class/bluetooth/hci0/power/runtime_enabled
# Brightness: cat /sys/class/backlight/intel_backlight/brightness
while true; do
    xsetroot -name "HD $(df -h | awk '{ if ($6 == "/home") print $4 }') | Mem $(free -h | awk '(NR==2){ print $4 }') | Bat $(cat /sys/class/power_supply/BAT0/capacity)% | Lux $(cat /sys/class/backlight/intel_backlight/brightness)% | Vol $(amixer -c 1 get Master | awk -F'[][]' 'END{ print $2 }') | $(date +"%F %R") $(cat /sys/class/net/wlp2s0/operstate)"
	sleep 1m
done &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
